datasource:
  postgres:
    url: ${RW_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${RW_DB_USERNAME}
    password: ${RW_DB_PASSWORD} 
    configuration:
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 6
api:
  auth-service:
    http-endpoint:
      host: http://random-walk.ru/auth
    username: ${RW_API_AUTH_USERNAME}
    password: ${RW_API_AUTH_PASSWORD}
  google-oauth2:
    email: ${GOOGLE_USER_EMAIL}
    password: ${GOOGLE_USER_PASSWORD}

