datasource:
  database-settings:
    url: ${RW_DB_URL}
    driver-class-name: org.postgresql.Driver
    configuration:
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 6
    ssh:
      ssh-host: ${SSH_HOST}
      ssh-port: ${SSH_PORT}
      ssh-user: ${SSH_USER}
      ssh-private-key: ${SSH_PRIVATE_KEY}
      remote-host: ${SSH_REMOTE_HOST}
      remote-port: ${SSH_REMOTE_PORT}
  auth:
    username: ${RW_AUTH_DB_USERNAME}
    password: ${RW_AUTH_DB_PASSWORD}
  matcher:
    username: ${RW_MATCHER_DB_USERNAME}
    password: ${RW_MATCHER_DB_PASSWORD}
  chat:
    username: ${RW_CHAT_DB_USERNAME}
    password: ${RW_CHAT_DB_PASSWORD}
  club:
    username: ${RW_CLUB_DB_USERNAME}
    password: ${RW_CLUB_DB_PASSWORD}
api:
  token: ${TEST_TOKEN}
  autotest-token: ${AUTOTEST_TOKEN}
  websocket:
    url: wss://random-walk.ru:44424/chat/ws
    message-endpoint: /app/sendMessage
    chat-endpoint: /topic/chat/
  auth-service:
    http-endpoint:
      host: https://random-walk.ru:44424/auth
    username: ${RW_API_AUTH_USERNAME}
    password: ${RW_API_AUTH_PASSWORD}
  matcher-service:
    http-endpoint:
      host: https://random-walk.ru:44424/matcher
  chat-service:
    http-endpoint:
      host: https://random-walk.ru:44424/chat
  graphql:
    base-uri: https://random-walk.ru:44424
    request-path: /graphql
spring:
  config:
    import:
    - classpath:users.yml
    - classpath:clubs.yml
test-management-system:
  token: ZlJPWVRzZExIME5nbzQ3VzR0

